decred/dcrwebapi

Dockerfile
README.md
php.ini

Added Docker config for running the API inside a container

Dockerized deployment setup

---

service.go

This PR has been discussed at #6

feature: add dcr.pos.fans pool as Oscar

---

service.go

service: randomize gsd response.

---

service.go

add ray stake pool https://dcrpos.idcray.com

---

service.go

Added required data for https://github.com/decred/dcrweb/pull/224. While I was at it, I added the proportion missed so we don't have to compute it in JS. Also fixed a few typos.

Add launch dates and proportion missed to API response

---

service.go

add a new stakepool https://tokensmart.io   Has been audited

add a new stakepool

---

service.go

Added stakepool Sierra in service.go

Add new stakepool

---

service.go

Added stakepool Scarmani in service.go

Added new stakepool to service.go

---

service.go

updating API to add my new pool

added new coinmine.pl stake pool

---

service.go

add Staked (created PR per dhill)

add Staked

---

service.go

added the new pool entry for https://dcrpool.dittrex.com

added new dittrex pool

---

service.go

added the test dittrext pool that was around for many months , but didnt have time list it before as dhill asked to couple months ago

update the file for the new entry

---

Dockerfile

docker: use alpine to build and serve

---

service.go

Pull request requesting that VSP 99split.com be added to dcrwebapi.

Adding VSP 99split.com

---

service.go

Revert "Remove raqamiya.net VSP"

---

helper.go
service.go

This was used on the decred.org site a long time ago, but it is not used anymore.
https://api.decred.org/?c=dic

Remove svg download count

---

service.go

Removes duplication and enables reusing the code later for contacting vspd instances.

Extract HTTP code for reuse later.

---

service.go

New URL is `/?c=vsp`
Example response:
```json
"http://localhost:8800":{"network":"testnet","launched":1591315200,"lastupdated":1594639340,"apiversions":[1],"feepercentage":3,"closed":false,"voting":3,"voted":0,"revoked":1}}
```
Closes #98

Add method to retrieve vspd info

---

README.md
docs/api.md

Also an introductory paragraph, and a paragraph about adding new VSPs.
Closes #105

Add API details to README

---

service.go

First vote on mainnet, please add our VSPD

Adding 99split.com

---

service.go

Created a new pull request because i made something wrong n the last one

Adding VSPD decredbrasil.com

---

service.go

It took a while but we finally have a vote.
https://dcrvsp.ubiqsmart.com
Thanks!

Add dcrvsp.ubiqsmart.com

---

service.go

We have had 2 votes.
https://vsp.dcr.farm/
Thanks!

Add vsp.dcr.farm

---

service.go

It's been unresponsive for weeks.

Remove test.stakey.net due to inactivity

---

service.go

One ticket already voted successfully on mainnet.

Add 123.dcr.rocks to VSP list

---

service.go

This is how the response looks with block height included: https://pastebin.com/QK4zr7Gi
Closes #136

Include blockheight in gsd response.

---

service.go

removed dcrpool

---

service.go

remove legacy stakepool pool.d3c.red

---

service.go

Add vspd.bass.cf to list of vspd providers
Mainnet tickets have been staked

Add vspd.bass.cf to list of vspd providers

---

.github/workflows/go.yml
helper.go
lint.sh
service.go

Just a bit of tidying up and refactoring

General housekeeping

---

service.go

- Project is winding down - removing it from the list now that there are no more live tickets

Remove synergy crypto VSPd

---

service.go

Offline for ~2 weeks and not responding to Matrix or Email.

Remove vspd.stakey.com.

---

service.go

Offline for >7 days and admin not responding on Matrix.
@kiahmed @kazi-nutanix
If someone has the VSP's support e-mail address please share or shoot them a message so they can check out what's wrong.

Remove dcrvsp.dittrex.com

---

service.go

99Split is closing, please remove us from the list of active vsps

99Split is closing
