.gitignore
LICENSE
service.go

Update the URL for VSP Bravo from "https://dcr.stakepool.net" to "https://dcr.blue".

dcr.stakepool.net is now dcr.blue

---

service.go

Sorry, please ignore: https://github.com/decred/dcrwebapi/pull/69.

remove pool entry for https://dcr.grassfed.network

---

service.go

Name "Tango" chosen arbitrarily. Launch date matching mainnet decredvoting.com.

Add missing testnet VSP

---

service.go

Service has proven to be unreliable - repeatedly gone offline, a very high miss rate, and not contactable.

remove dcr.pos.fans

---

service.go

These two VSPs have had broken registration (email errors) since at least December 19th. There have been multiple attempts to contact the operators.
https://tokensmart.io was added in #23 by @qukuailianyonghu
https://dcrpos.idcray.com was added in #17 by @saymissme

Remove VSPs with broken registration.

---

service.go

CSRF error is being shown when attempting to add a pubkeyaddr to a new account:
```Forbidden - CSRF token invalid```
Operator `@utyosov:decred.org` has been notified on Matrix but not responded.

Remove raqamiya.net VSP

---

service.go

Keys are already used in the map - they dont need to be stored again

Dont duplicate stakepool keys

---

service.go

Location directives allowing dcrstakepool and vspd to co-exist on the same domain do not (and actually have never) required moving api endpoints. See nginx samples provided in vspd issue #159. The invalid api path has been deprecated and removed.

vspd domain correction

---

service.go

This removes decred.staked.us
ref: https://twitter.com/staked_us/status/1329173484598124546

Remove staked.us VSP

---

service.go

Service has been offline for a long time and shows no signs of coming back.

Remove vspd.realprivacy.cc testnet  VSP.

---

service.go

VSPD has now had a vote! 
https://ultravsp.uk/
This is the vspd version of ultrapool.eu . Due to Brexit uncertainty I'm moving to a .uk domain name in case something unexpected happpens and I get forced to change domain names later.

Add ultravsp.uk

---

service.go

Brexit is going to mean that ultrapool.eu will stop resolving in the new year, so can you update this to point to it's new DNS entry.
Thanks.

Changed ultrapool.eu -> legacy.ultravsp.uk

---

service.go

Both of these pools have been offline for a long time.
FYI @atticlab (everstake) @eball (mega)

Remove unresponsive VSPs.

---

service.go

The following operators have not been active in the community for some time, and show no signs of upgrading to vspd. Between them they currently hold 303 live tickets.
- @dyrk (https://stakepool.dcrstats.com)
- @tpruvot (https://stakepool.eu)
- @gsampathkumar (https://yieldwallet.io)

Remove VSP operators who haven't updated to vspd.

---

.github/workflows/go.yml

Linter `golint` has been deprecated and replaced with `revive`.

Update to golangci-lint 1.40.1.

---

service.go

Return vspd version.

---

service.go

https://stakey.net => redirects to vspd
https://dcr.farm => redirects to vspd
https://testnet.decredvoting.com => down
https://dcrstakedinner.com => bad ssl and 502

Remove non working legacy pools

---

service.go

Permanently closed (but still alive for the last live tickets)

Remove stakepool.eu too

---

service.go

Reporting zero live/immature tickets.
FYI @99split

Remove legacy 99split VSP.

---

.gitignore
main.go
service.go

This commit adds two new optional fields to the `c=vsp` command:
1. `BlockHeight`.
2. `EstimatedNetworkProportion`.
Closes #142.

VSPs: Add `BlockHeight` & `EstimatedNetworkProportion`.

---

service.go

Offline for >14 days and admin not responding on Matrix.
@lealife

Remove dcrpool.ibitlin.com

---

service.go

I noticed the old URL is now redirecting to https://decred.stake.fun and the branding on their site also reflects the change.
@feeleep75 could you please confirm this change?

Change coinmine.pl URL to decred.stake.fun

---

.github/workflows/docker.yml
.github/workflows/go.yml
Dockerfile
docs/api.md
service.go

I have confirmed that this works with the current dcrweb code, it just ignores the new fields.

Handle expired/missed ticket counts from VSPs.

---

service.go

Unfortunately we have to shut down our VSP. As soon as 123.dcr.rocks has been removed from the list we will stop accepting new tickets and then shut down the servers in a few months once all live tickets have been voted.

Remove 123.dcr.rocks
